# Generated by Django 4.2.2 on 2023-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('------', '------'), ('Ж', 'Ж')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('Seller', 'Seller'), ('------', 'Customer'), ('Moderator', 'Moderator')], default='------', max_length=20),
        ),
    ]
