# Generated by Django 4.2.2 on 2023-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('------', '------'), ('Ж', 'Ж')], default='------', max_length=20),
        ),
    ]
