# Generated by Django 4.2.2 on 2023-08-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_user_address_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
