# Generated by Django 4.2.2 on 2023-07-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderator',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Moderator', 'Moderator'), ('------', 'Customer')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('------', '------'), ('Ж', 'Ж'), ('М', 'М')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
