# Generated by Django 4.2.2 on 2023-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_moderator_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moderator',
        ),
        migrations.AddField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('------', 'Customer'), ('Moderator', 'Moderator'), ('Seller', 'Seller')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('------', '------'), ('Ж', 'Ж')], default='------', max_length=20),
        ),
    ]
