# Generated by Django 4.2.2 on 2023-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('------', 'Customer'), ('Moderator', 'Moderator'), ('Seller', 'Seller')], default='------', max_length=20),
        ),
    ]
