# Generated by Django 4.2.2 on 2023-08-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_user_in_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='in_group',
        ),
    ]
