# Generated by Django 4.2.2 on 2023-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_user_moderator_user_in_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('------', '------'), ('М', 'М'), ('Ж', 'Ж')], default='------', max_length=20),
        ),
    ]
