# Generated by Django 4.2.2 on 2023-07-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('------', '------'), ('Ж', 'Ж')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('Moderator', 'Moderator'), ('------', 'Customer'), ('Seller', 'Seller')], default='------', max_length=20),
        ),
    ]
