# Generated by Django 4.2.2 on 2023-07-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_user_gender_alter_user_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Ж'), ('------', '------'), ('М', 'М')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('Seller', 'Seller'), ('------', 'Customer'), ('Moderator', 'Moderator')], default='------', max_length=20),
        ),
    ]
