# Generated by Django 4.2.2 on 2023-08-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_user_gender_alter_user_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж'), ('------', '------')], default='------', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('------', 'Customer'), ('Moderator', 'Moderator'), ('Seller', 'Seller')], default='------', max_length=20),
        ),
    ]
