# Generated by Django 4.2.2 on 2023-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_user_gender_alter_user_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Ж'), ('------', '------'), ('М', 'М')], default='------', max_length=20),
        ),
    ]
