# Generated by Django 4.2.2 on 2023-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='in_group',
            field=models.CharField(choices=[('Moderator', 'Moderator'), ('------', 'Customer'), ('Seller', 'Seller')], default='------', max_length=20),
        ),
    ]
