// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thrid_angle.Database.RestAPI.Database;

#nullable disable

namespace Thrid_angle.Database.RestAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230715082257_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Thrid_angle.Database.RestAPI.DTO.Baskets", b =>
                {
                    b.Property<Guid>("IdBasket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdBasket");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("Thrid_angle.Database.RestAPI.DTO.BookCard", b =>
                {
                    b.Property<Guid>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdBook");

                    b.ToTable("BookCard");
                });

            modelBuilder.Entity("Thrid_angle.Database.RestAPI.DTO.OrderCard", b =>
                {
                    b.Property<Guid>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdOrder");

                    b.ToTable("OrderCard");
                });

            modelBuilder.Entity("Thrid_angle.Database.RestAPI.DTO.QuoteCard", b =>
                {
                    b.Property<Guid>("IdQuote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdQuote");

                    b.ToTable("QuoteCard");
                });

            modelBuilder.Entity("Thrid_angle.Database.RestAPI.DTO.RequestCard", b =>
                {
                    b.Property<Guid>("IdRequestCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRequestCard");

                    b.ToTable("RequestCard");
                });

            modelBuilder.Entity("Thrid_angle.Database.RestAPI.DTO.UserCard", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("UserCard");
                });
#pragma warning restore 612, 618
        }
    }
}
