# Generated by Django 4.2.2 on 2023-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидает', 'Ожидает'), ('В обработке', 'В обработке'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Закрыт', 'Закрыт')], default='Ожидает', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Ожидает', 'Ожидает'), ('В обработке', 'В обработке'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Закрыт', 'Закрыт')], default='Ожидает', max_length=20),
        ),
    ]
