# Generated by Django 4.2.2 on 2023-08-06 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketapp', '0007_alter_basket_status_alter_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='status',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Закрыт', 'Закрыт'), ('Ожидает', 'Ожидает'), ('Готов к отгрузке', 'Готов к отгрузке')], default='Ожидает', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Закрыт', 'Закрыт'), ('Ожидает', 'Ожидает'), ('Готов к отгрузке', 'Готов к отгрузке')], default='Ожидает', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basketapp.order'),
        ),
    ]
