# Generated by Django 4.2.2 on 2023-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0008_remove_basket_status_alter_request_status_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Закрыт', 'Закрыт'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Ожидает', 'Ожидает'), ('В обработке', 'В обработке')], default='Ожидает', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Закрыт', 'Закрыт'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Ожидает', 'Ожидает'), ('В обработке', 'В обработке')], default='Ожидает', max_length=20),
        ),
    ]
