# Generated by Django 4.2.2 on 2023-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='comment',
            name='starts',
            field=models.CharField(choices=[('3', '3'), ('1', '1'), ('2', '2'), ('4', '4'), ('5', '5')], default='1', max_length=20),
        ),
    ]
