# Generated by Django 4.2.2 on 2023-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='person',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
