# Generated by Django 4.2.2 on 2023-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_comment_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='starts',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20),
        ),
    ]
