# Generated by Django 4.2.2 on 2023-08-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=128)),
                ('foto', models.ImageField(blank=True, upload_to='news_images')),
            ],
        ),
    ]
