# Generated by Django 4.2.2 on 2023-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_comment_starts'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='news',
            name='foto',
            field=models.ImageField(blank=True, upload_to='news_images'),
        ),
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='starts',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('1', '1'), ('3', '3'), ('5', '5')], default='1', max_length=20),
        ),
    ]
