# Generated by Django 4.2.2 on 2023-07-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_news_description_news_foto_news_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='starts',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('5', '5'), ('3', '3'), ('1', '1')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
    ]
