# Generated by Django 4.2.2 on 2023-08-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_comment_starts'),
        ('mainapp', '0007_quote_alter_comment_starts'),
    ]

    operations = [
    ]
