# Generated by Django 4.2.2 on 2023-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_merge_20230801_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='starts',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('2', '2'), ('1', '1'), ('5', '5')], default='1', max_length=20),
        ),
    ]
