# Generated by Django 4.2.2 on 2023-08-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_comment_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='starts',
            field=models.CharField(choices=[('4', '4'), ('1', '1'), ('3', '3'), ('2', '2'), ('5', '5')], default='1', max_length=20),
        ),
    ]
